### ISSUE TITLE
UIColor section mixes HSBA with HSVA

### ISSUE THREAD

**Issue by guti7** [soggybag/ios-ui-design#3]
@soggybag when you introduce the two models of color you use HSBA but then when you are defining it you use value instead of brightness. 
In the same line, you mention that "saturation of 0 is black". I think it's supposed to be brightness instead. 

[uicolor](https://github.com/soggybag/ios-ui-design/tree/master/01-frame-bounds-center-color#uicolor)

**Comment by soggybag** [comment]
Value is the term used for a color's light or darkness. It's an art term. Not a computer term. The HSB color model is the same as the HSV color model. Either way brightness or value refers to how light or dark a color is. If you took out the hue you'd be left with just a gray value. 

https://www.google.com/#safe=off&q=HSB+vs+HSV&*

**Comment by guti7** [comment]
@soggybag so they are the same but doesn't a color's value of 0 mean that the color turns black, and a saturation of 0 turns the color white? I think I'm getting confused.

**Comment by soggybag** [comment]
I guess when I say value I'm talking about how light or dark a color is. If
you converted every color to a gray value.

Brightness on the other hand is used by the computer as part of the HSB
color model.

The best way to get a handle on HSB is to open Xcode. Go to storyboard.
Click the background view. Set the background color. When this opens the
color picker choose HSB from the menu, it's usually RGB by default. You can
play with the HSB sliders and see how they affect the color.

**Comment by guti7** [comment]
Thanks @soggybag !
